FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
RUN apt-get update && apt-get install -y libgdiplus
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . ./
RUN cp ./Container/NuGet.Config "$HOME/.nuget/NuGet/NuGet.Config"
RUN dotnet restore
RUN dotnet build "KittyBot.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "KittyBot.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "KittyBot.dll"]
